print("Please enter your times table:")
q = (input())
#9/answer = int(Question) + int(2)
#print(str(Question) + "x" + "1" + "=" + int(Question) * int(1))
#print(q + " X" + " 1" + " =" + " "+ q*1)
# for i in range(1,11):
# print(f'{q} x {i}  = {int(q)*i}')
print(f'{q} x 1 = {int(q)*1}')
print(f'{q} x 2 = {int(q)*2}')
print(f'{q} x 3 = {int(q)*3}')
print(f'{q} x 4 = {int(q)*4}')
print(f'{q} x 5 = {int(q)*5}')
print(f'{q} x 6 = {int(q)*6}')
print(f'{q} x 7 = {int(q)*7}')
print(f'{q} x 8 = {int(q)*8}')
print(f'{q} x 9 = {int(q)*9}')
print(f'{q} x 10 = {int(q)*10}')

